<?php
//~ Template for detail.php
// variables:
//  $todo - TODO to be displayed
//  $tooLate - if the task should have been done already

/* @var $todo Todo */
?>

<h1>
    <?php if ($tooLate): ?>
        <img src="img/exclamation.png" alt="" title="Deveria já estar pronto!" />
    <?php endif; ?>
    <?php echo Utils::escape($todo->getTitle()); ?>
</h1>

<table class="detail">
    <tr>
        <th>Prioridade</th>
        <td><img src="img/priority/<?php echo $todo->getPriority(); ?>.png" alt="Prioridade <?php echo $todo->getPriority(); ?>" title="Prioridade <?php echo $todo->getPriority(); ?>" /></td>
    </tr>
    <tr>
        <th>Registro</th>
        <td><?php echo Utils::escape(Utils::formatDateTime($todo->getCreatedOn())); ?></td>
    </tr>
    <tr>
        <th>Prazo</th>
        <td>
            <?php if ($tooLate): ?><span class="too-late"><?php endif; ?>
            <?php echo Utils::escape(Utils::formatDateTime($todo->getDueOn())); ?>
            <?php if ($tooLate): ?></span><?php endif; ?>
        </td>
    </tr>
    <tr>
        <th>Última Modificação</th>
        <td><?php echo Utils::escape(Utils::formatDateTime($todo->getLastModifiedOn())); ?></td>
    </tr>
    <tr>
        <th>Descrição</th>
        <td><?php echo Utils::escape($todo->getDescription()); ?></td>
    </tr>
    <?php if(Utils::escape($todo->getComment())): ?>
        <tr><th>Comentário</th>
        <td><?php echo Utils::escape($todo->getComment()); ?></td>
        </tr>
    <?php endif: ?>
    <tr>
        <th>Status</th>
        <td><img src="img/status/<?php echo $todo->getStatus(); ?>.png" alt="" title="<?php echo Utils::capitalize($todo->getStatus()); ?>" class="icon" /></td>
    </tr>
    <tr>
        <td colspan="2">&nbsp;</td>
    </tr>
    <tr>
        <th></th>
        <td>
            <div class="statuses">
            <?php foreach (Todo::allStatuses() as $status): ?>
                <?php if ($status != $todo->getStatus()): ?>
                    <a href="<?php echo Utils::createLink('altera-status', array('id' => $todo->getId(), 'status' => $status)); ?>" title="Altera o status da RNC para <?php echo Utils::capitalize($status); ?>." class="change-status-link"
                       ><img src="img/status/<?php echo $status; ?>.png" alt="" title="Alterar para <?php echo Utils::capitalize($status); ?>." class="icon" /></a>
                <?php else: ?>
                    <img src="img/status/<?php echo $status; ?>-disabled.png" alt="" title="Este RNC está <?php echo Utils::capitalize($status); ?>." class="icon" />
                <?php endif; ?>
            <?php endforeach; ?>
            </div>
            <div class="actions">
                <a href="<?php echo Utils::createLink('add-edit', array('id' => $todo->getId())); ?>"><img src="img/action/edit.png" alt="" title="Edita" class="icon" /></a>
                <a href="<?php echo Utils::createLink('delete', array('id' => $todo->getId())); ?>" id="Exclui-Link"><img src="img/action/delete.png" alt="" title="Exclui" class="icon" /></a>
            </div>
        </td>
    </tr>
</table>

<p>
    <?php $backLink = Utils::createLink('list', array('status' => $todo->getStatus())); ?>
    <a href="<?php echo $backLink; ?>"><img src="img/action/back.png" alt="" title="Back to the list." class="icon"/></a>&nbsp;
    <a href="<?php echo $backLink; ?>">To the list</a>
</p>

<div id="delete-dialog" title="Delete this TODO?">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Este RNC será excluído. Confirma?</p>
</div>
<div id="change-status-dialog">
    <form id="change-status-form" method="post">
        <fieldset>
            <div class="field">
                <label>Comentário:</label>
                <textarea name="comment" cols="1" rows="1"></textarea>
            </div>
        </fieldset>
    </form>
</div>
