<?php
//~ Template for detail.php
// variables:
//  $todo - TODO to be displayed
//  $tooLate - if the task should have been done already

/* @var $todo Todo */
// Mapeando os campos
    $banco = 'white';
    $campo = array(
        'Número' => Utils::escape($todo->getNumero()),
        'Abertura' => Utils::escape(Utils::formatDateTime($todo->getCreatedOn())),
        'Prazo' => Utils::escape(Utils::formatDateTime($todo->getDueOn())),
        'Detalhamento' => Utils::escape($todo->getDescricao()),
        'Origem' => Utils::escape($todo->getOrigem()),
        'Tipo Ação' => Utils::escape($todo->getTipoacao()),
        'Processo' => Utils::escape($todo->getProcesso()),
        'Responsável pela Identificação' => Utils::escape($todo->getIdentificador()),
        'Causa da Não Conformidade' => Utils::escape($todo->getCausa()),
        'Ação Imediata' => Utils::escape($todo->getImediata()),
        'Ação Corretiva' => Utils::escape($todo->getCorretiva()),
        'Responsável pela Implementação' => Utils::escape($todo->getImplementador()),
        'Prazo para a Eliminação' => Utils::escape(Utils::formatDateTime($todo->getEliminacao())),
        'Novo Prazo' => Utils::escape(Utils::formatDateTime($todo->getEliminacao_novo())),
        'Registro da Verificação da Eficácia' => Utils::escape($todo->getComment()),
        'Responsável pela Verificação' => Utils::escape($todo->getRespVerificacao()),
        'A Ação foi Eficaz?' => Utils::escape($todo->getEficaz()),
        'Conclusão' => Utils::escape(Utils::formatDateTime($todo->getEficazData())),
        'Novo RNC' => Utils::escape($todo->getNovoRnc()),
    );
?>

<h1>
    <?php if ($tooLate): 
        if($todo->getEliminacao() == $todo->getCreatedOn())
            if($todo->getEliminacao_novo() == $todo->getCreatedOn())
                if($todo->getEficazData() == $todo->getCreatedOn())
        : ?>
        <img src="img/exclamation.png" alt="" title="Prazo esgotado!" />
    <?php endif; endif;?>
    <?php echo Utils::escape($todo->getTitle()); ?>
</h1>
<table>
<?php
    if(array_key_exists('Número',$campo)){
        //echo "Número existe<br>";
    }
    echo "<table class=\"detail\">";
            $x = 1;
        foreach($campo as $key => $item){
            if($item <> null){
                if(($key=='Prazo para a Eliminação')||($key=='Novo Prazo')||($key=='Conclusão')){
                    if($item<>Utils::escape(Utils::formatDateTime($todo->getCreatedOn()))){
                        if($x % 2 == 0){
                            $cor='white';
                        }else{
                            $cor='';
                        }
                    echo "<tr bgcolor=".$cor." >"
                        . "<th width=200px>".$key." </th>
                        <td>".$item."</td>
                        </tr>";
                        $x++;
                    }
                }else{
                   if($x % 2 == 0){
                      $cor='white';
                   }else{
                      $cor='';
                   }
                    echo "<tr bgcolor=".$cor." >"
                        . "<th width=200px>".$key." </th>
                        <td>".$item."</td>
                        </tr>";
                        $x++;
                }
            }
        }
?>
    <tr>
        <th>Status</th>
        <td><img src="img/status/<?php echo $todo->getStatus(); ?>.png" alt="" title="<?php echo Utils::capitalize($todo->getStatus()); ?>" class="icon" /></td>
    </tr><tr>
        <td colspan="2">&nbsp;</td>
    </tr><tr>
        <th></th>
        <td>
            <div class="statuses">
            <?php foreach (Todo::allStatuses() as $status): ?>
                <?php if ($status != $todo->getStatus()): ?>
                    <a href="<?php echo Utils::createLink('altera-status', array('id' => $todo->getId(), 'status' => $status)); ?>" title="Altera o status da RNC para <?php echo Utils::capitalize($status); ?>." class="change-status-link" ><img src="img/status/<?php echo $status; ?>.png" alt="" title="Alterar para <?php echo Utils::capitalize($status); ?>." class="icon" /></a>
                <?php else: ?>
                    <img src="img/status/<?php echo $status; ?>-disabled.png" alt="" title="Este RNC está <?php echo Utils::capitalize($status); ?>." class="icon" />
                <?php endif; ?>
            <?php endforeach; ?>
            </div>
            <div class="actions">
                <a href="<?php echo Utils::createLink('add-edit', array('id' => $todo->getId())); ?>"><img src="img/action/edit.png" alt="" title="Edita" class="icon" /></a>
                <a href="<?php echo Utils::createLink('delete', array('id' => $todo->getId())); ?>" id="delete-link"><img src="img/action/delete.png" alt="" title="Exclui" class="icon" /></a>
            </div>
        </td>
    </tr>
</table>

<p>
    <?php $backLink = Utils::createLink('list', array('status' => $todo->getStatus())); ?>
    <a href="<?php echo $backLink; ?>"><img src="img/action/back.png" alt="" title="Retornar à lista." class="icon"/></a>&nbsp;
    <a href="<?php echo $backLink; ?>">Retornar à lista</a>
</p>

<div id="delete-dialog" title="Esclui este RNC?">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Este RNC será excluído. Confirma?</p>
</div>
<div id="change-status-dialog">
    <form id="change-status-form" method="post">
        <fieldset>
            <div class="field">
                <label>Registro da Verificação da Eficácia:</label>
                <textarea name="comment" cols="41" rows="1"></textarea>
            </div>
        </fieldset>
    </form>
</div>
