<?php ?>
<h1>Bem-vindo!</h1>

<p class="p">Bem-vindo ao programa de <b>R</b>egistros de <b>N</b>ão <b>C</b>onformidades <b>(RNC)</b>.</p>
    <p>Este programa tem como objetivo a distribuição de responsabilidades,<br>garantindo maior trabalho em equipe, agilidade e eficácia nas tratativas das não conformidades:</p>
	<br>
<ul class="p">
    <li>registrando não conformidades;</li>
    <li>acompanhando as soluções tomadas;</li>
    <li>acompanhando os vencimentos dos prazos.</li>
</ul>
<p class="p"></p>
<p class="p"><b></b></p>
